# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MountainListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PINRemoteImage', '~>3.0.3'
  pod 'MaterialComponents/Buttons', '~>120.0.0'

  # Pods for MountainListApp


end
